### ISSUE TITLE
Availibility PDP

### ISSUE THREAD

**Issue by elisabethschneider** [sphereio/sphere-sunrise#124] opened 2015-07-22 15:32 UTC
if a product is on stock, the customer is able to see a green symbol with the information that the product is available and it can be delivered in 2-5 days

**Comment by schleichardt** [comment] 2015-07-22 15:51
duplicate of https://github.com/sphereio/sphere-sunrise/issues/115

**Closed by schleichardt** 2015-07-22 15:51 UTC
Labels: duplicate, pdp
